### ISSUE TITLE
console.resize not working

### ISSUE THREAD

**Issue by dralexan** [IrisDynamics/IrisControls4#12]
Testing out console commands, trying to resize. Testing out using EsgleSDK_2.0/examples/EagleSDK_GUI_example

console.move works

Here is the code I'm adding to the gui.h file after line 60:
      console.move(0,5);
      console.resize(15,15);

Without the resize command: 
![image](https://user-images.githubusercontent.com/84802205/192611606-c71484b6-a335-4230-af3e-332a62f9bb11.png)
With the resize command:
![image](https://user-images.githubusercontent.com/84802205/192611650-fdb2792b-dddc-4819-b196-212258aeb432.png)

**Comment by dbeddoes** [comment]
As per the [documentation ](https://wiki.irisdynamics.com/index.php?title=IrisControlsAPI4_Overview#The_Console), the minimum size of the console is 20 rows and 10 columns. 
Therefore:
console.resize(15,15);
will always fail.
